GRANT CONNECT, CREATE SESSION TO gestore;
GRANT ALL ON Utente TO gestore;
GRANT ALL ON Promozione TO gestore;
GRANT ALL ON Promozione_fedelta TO gestore;
GRANT ALL ON Carrello TO gestore;
GRANT ALL ON Biglietto TO gestore;
GRANT SELECT ON Recensione TO gestore;
GRANT DELETE ON Recensione TO gestore;
GRANT ALL ON Spettacolo TO gestore;
GRANT ALL ON Sala TO gestore;
GRANT ALL ON Cinema TO gestore;
GRANT ALL ON Posto TO gestore;
GRANT ALL ON Film TO gestore;
GRANT ALL ON Genere_film TO gestore;
GRANT ALL ON Genere TO gestore;
GRANT ALL ON Diretto_da TO gestore;
GRANT ALL ON Recitato_da TO gestore;
GRANT ALL ON Professionista TO gestore;
GRANT ALL ON Compagnia_di_produzione TO gestore;
GRANT EXECUTE update_data_pagamento TO gestore;
GRANT EXECUTE cliente_del_mese TO gestore;
GRANT EXECUTE inserisci_posti TO gestore;
GRANT EXECUTE annulla_ordine TO gestore;
GRANT EXECUTE FakeUser TO gestore;
GRANT EXECUTE Assegna_carta_fedelta TO gestore;
GRANT EXECUTE elimina_biglietti_scaduti TO gestore;


GRANT CONNECT, CREATE SESSION TO user;
GRANT INSERT ON Utente TO user;
GRANT INSERT ON Carrello TO user;
GRANT INSERT ON Biglietto TO user;
GRANT INSERT ON Carta_di_credito TO user;
GRANT DELETE ON Carta_di_credito TO user;
GRANT ALL ON Recensione TO user;
GRANT SELECT ON Spettacolo TO user;
GRANT SELECT ON SalaIMAX3D TO user;
GRANT SELECT ON MediaRecensione TO user;
GRANT SELECT ON RegistaAttore TO user;
GRANT SELECT ON VistaFilm TO user;
GRANT SELECT ON Orari_spettacoli TO user;
GRANT EXECUTE update_data_pagamento TO user;
GRANT EXECUTE annulla_ordine TO user;
GRANT EXECUTE auto_acquista TO user;
GRANT EXECUTE elimina_biglietti_scaduti TO user;